# Generated by Django 5.1 on 2024-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adelanto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='horas_laboradas',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
